# Generated by Django 5.0.1 on 2024-02-05 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('date_receipt', models.DateTimeField(auto_now_add=True)),
                ('store', models.IntegerField()),
                ('image_field', models.ImageField(blank=True, default=None, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('date_visit', models.DateTimeField(auto_now_add=True)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('products', models.ManyToManyField(to='dz_app4.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dz_app4.user')),
            ],
        ),
    ]
