# Generated by Django 5.0.1 on 2024-02-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz_app4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='dz_app4.cartitem'),
        ),
    ]
