# Generated by Django 5.0.1 on 2024-02-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dz_app4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.IntegerField(default=0),
        ),
    ]
